# Generated by Django 2.2.2 on 2019-07-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='cetpa@gmail.com', max_length=100)),
                ('mobile', models.BigIntegerField(default='1234567890')),
                ('password', models.CharField(default='cse', max_length=100)),
            ],
        ),
    ]
