# Generated by Django 2.2.2 on 2019-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190720_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='LoginDetails',
        ),
    ]
