# Generated by Django 2.2.2 on 2019-07-20 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190720_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='mobile',
        ),
        migrations.AddField(
            model_name='logindetails',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
