# Generated by Django 2.2.2 on 2019-07-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190720_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginDetails',
            new_name='Signup',
        ),
    ]
