# Generated by Django 2.2.2 on 2019-08-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='a@g.com', max_length=100),
        ),
    ]
